version: "3"

services:
  backend:
    build: ./backend/
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    ports:
      - 3000:3000
    command: npm run dev
  
  client-angular:
    hostname: localhost
    build: ./client-angular
    ports:
      - 4200:4200
