version: "3"

services:
  client-angular:
    build: ./client-angular
    volumes:
      - ./client-angular:/app/client-angular
    ports:
      - 4200:4200

  backend:
    build: ./backend/
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    ports:
      - 3000:3000
    command: npm run dev